var GAME_LEVELS = [
 ["                                 yy                                             ",
   "                 yy                                     yy                      ",
   "                                                                                ",
   "                                           yy                                   ",
   "                                                              yy                ",
   "             yy                                                                 ",
   "                                             b                                  ",
   "    yy                                     xxxx                                 ",
   "                        yy          o o                        b                ",
   "                                    xxxx                      xxxx              ",
   "                                                 xx    xx             xxx       ",
   "                           yy                                               xx  ",
   "  xx           yy                         o o                 yy             x  ",
   "  x                                       xxxx                               x  ",
   "  x                                                       yy               p x  ",
   "  x                     o          xxxx                                 x  x x  ",
   "  x  @             b               x  x                               x x!!x!x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxx  ",
   "             x!!x         x   x                  x     x                        ",
   "             xxxx         x!!!x                  x!!!!!x                        ",
   "                          x!!!x                  x!!!!!x                        ",
   "                          xxxxx                  xxxxxxx                        ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                  xxxxxxx                                    x!x  ",
   "                                              b  o                                                           x!x  ",
   "                                      xxx!xxxxxxxxx                         xx                                x!x ",
   "                                      xx!!!!!!!!!!xx                         xx                               x!x ",
   "                                       xxxxxxxxxx!!x               xxxxx       x                  o   o   o  x!x  ",
   "                                                xx!xx              o   o       x                           pxx!x  ",
   "                                                 x!x                           x              xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx       xxx     x   x       x         !!!!!!!!!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx           !xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                          o            x       xxxx!!!!!xxxx                                      ",
   "                                                                  xxxxxxx         xx          xxx                 ",
   "                                   o      xx                                      x          x x                  ",
   "                                                                                   x         x                    ",
   "                              xxx  o                                               xx        x                    ",
   "                                x                                                  x         x                    ",
   "                                x                           o  o     x   x         x         x                    ",
   "                                x   xxx        xx                    x   x         x         x                    ",
   "                   j            x   x                      xxxxxx    x   x   xxxxxxxxx       x                    ",
   "               xxxxxxxxx        x o x               xx               x   x   x               x                    ",
   " @            x         x       x   x                             xxxx   x   x       j       x                    ",
   "xxxx     o =  x         x       x   x                                x   xxxxx   xxxxxx      x                    ",
   "xxxxxxxxxxxxxxx         x      xx o xx         x      xxxxxxxxxxx    x     o     x x         x                    ",
   "!!!!!!!!!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!    x     =     x x         x                    ",
   "!!!!x x!!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                   ",
   "!!!!x x!!!!!!!x         x!!!!!x        x             xx!!!!!!xx !                    xx     xx                    ",
   "!!!!x x!!!!!!!x         x!!!!!x        x   o o      xx!!!!!!xx  !                     xxxxxxx                     ",
   "!!!!x x!!!!!!!x         x!!!!!xx   j   xxxxxxxxxxxxxx!!!!!!xx   !                                                 ",
   "!!!!x x!!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                 ",
   "!!!!x x!!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                 "],
  ["                                                                                                              ",
   "  x                                                                                                        x  ",
   "  x                                                                                             p          x  ",
   "  x                                                                                                        x  ",
   "  x                                                        ! !!!!                                          x  ",
   "  x                                                        vxxxxv                                          x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                 !!!!!!                                                                 x  ",
   "  x                                 vxxxxv                                                                 x  ",
   "  x                                                                                                x       x  ",
   "  x                                                                                                        x  ",
   "  x                                                        !!!        !!!          !!!!!!                  x  ",
   "  x                                                        !x!        !x!          vxxxxv                  x  ",
   "  x        xxx                           xxx               vx          x                                   x  ",
   "  x                                       x                 x   oooo   x       xxx                         x  ",
   "  x                                                         =  =  =  = =                                   x  ",
   "  x                                                         xxxxxxxxxxxx                                   x  ",
   "  x                                              x           x                                             x  ",
   "  x                                       xx   xxxx   xx    xx              x x                            x  ",
   "  x                                       x           x                    x!!!x                           x  ",
   "  x                   xxxx                                                  xxx                            x  ",
   "  x                                       xx          x                                                    x  ",
   "  x                                        = = = =    x            xxx                                     x  ",
   "  x                                                   x      =    = = =                         xx |x      x  ",
   "  x                                            = = = =x     o                xxx                           x  ",
   "  x                                  xx   xx          x              =          =                          x  ",
   "  x                           o   o   x   x           x    xx                xxv        xxx                x  ",
   "  x                                   x   x           x              x       = = =         =               x  ",
   "  x                           v!!    xxx xxx     o o  x!!!!!!!!!!!!!!x                                     x  ",
   "  x                            xxx x x xxx x          x!!!!!!!!!!!!!!x                                     x  ",
   "  x                                        x  |xxxxxxxxxxxxxxxxxxxxxxx               |          |   |       x  ",
   "  x                                       xx                                         xxx                   x  ",
   "  x                                       x                                         x!!!x                  x  ",
   "  x                                       x    =   =     =      =        =           vvv                   x  ",
   "  x                                       x                              xx                                x  ",
   "  x                                     x                                x   x                             x  ",
   "  x                                       x                              x                                 x  ",
   "  x                                         x     |xxxx|   |     |     x   x                               x  ",
   "  x                xxx                    x                                                                x  ",
   "  x                 x                      x                            xxx                                x  ",
   "  x                 x              x        x                           x x                                x  ",
   "  x                 x         xxxxxxxxxxxxx            x oo x    x oo  xx xx                               x  ",
   "  x      @    j     x         x           x!!x  =    =  =   x!!!!x    xx   xx     =  =    =  x=      x     x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
